module.exports = {
  purge: [],
  darkMode: false,
  theme: {
    extend: {
      transitionProperty: ["hover", "focus"],
      spacing: {
        90: "22.5rem",
        112: "28rem",
        128: "32rem",
        160: "40rem",
      },
      colors: {
        dark: "#272727",
        primary: "#7209b7",
        secondary: "#3a0ca3",
        tersiary: "#4361ee",
      },
    },
  },
  variants: {
    extend: {
      padding: ["hover", "group-hover", "even", "odd"],
      height: ["hover", "group-hover"],
      width: ["hover", "group-hover"],
      margin: ["hover", "group-hover"],
      borderWidth: ["hover", "group-hover"],
      fontWeight: ["hover", "group-hover"],
      transform: ["hover", "group-hover"],
      scale: ["hover", "group-hover"],
      translate: ["hover", "group-hover"],
      inset: ["hover", "group-hover"],
      space: ["hover", "group-hover"],
      transitionDelay: ["hover", "group-hover"],
      backgroundClip: ["hover", "active", "group-hover"],
      backgroundColor: ["hover", "active", "group-hover"],
      flexDirection: ["even", "odd"],
      textColor: ["hover", "active"],
      backgroundImage: ["first", "last", "even", "odd"],
      gradientColorStops: [
        "first",
        "last",
        "even",
        "odd",
        "group-hover",
        "hover",
        "active",
      ],
      fill: ["group-hover", "hover", "active"],
    },
  },
  plugins: [],
};
